import React from 'react';
import { Database, Binary, FileText, ShieldAlert, GitBranch, CheckCircle2 } from 'lucide-react';

export const ResourcesPage: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto space-y-12 animate-in fade-in duration-500">

            {/* Header */}
            <div className="text-center space-y-4">
                <h1 className="text-4xl font-bold text-white">Model & Data Transparency</h1>
                <p className="text-slate-400 text-lg">Detailed information about the EMBRYO-XAI system architecture and training data.</p>
            </div>

            {/* Disclaimer Card */}
            <div className="bg-amber-500/10 border border-amber-500/20 p-6 rounded-2xl flex gap-4">
                <ShieldAlert className="h-8 w-8 text-amber-500 flex-shrink-0" />
                <div className="space-y-2">
                    <h3 className="text-lg font-semibold text-amber-400">Research Use Only</h3>
                    <p className="text-amber-200/80 leading-relaxed">
                        This system is a prototype for **Research & Demonstration purposes only**.
                        It has **NOT** been evaluated or approved by the FDA, EMA, or any other regulatory health authority.
                        The predictions generated by this model should never be used as the primary basis for clinical decision-making
                        or embryo selection. Always consult with a certified embryologist.
                    </p>
                </div>
            </div>

            {/* Dataset Section */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 border-b border-dark-700 pb-4">
                    <Database className="h-6 w-6 text-primary-500" />
                    <h2 className="text-2xl font-bold text-white">The Dataset</h2>
                </div>
                <div className="grid md:grid-cols-2 gap-6">
                    <div className="bg-dark-800/50 p-6 rounded-xl border border-dark-700">
                        <h3 className="text-lg font-semibold text-white mb-2">Source Data</h3>
                        <p className="text-slate-400 text-sm leading-relaxed">
                            The model was trained on the <a href="https://www.kaggle.com/datasets/iamshahzaibkhan/human-blastocyst-dataset-for-ivf" target="_blank" rel="noreferrer" className="text-primary-400 hover:underline">Human Blastocyst Dataset for IVF</a>,
                            a curated collection of microscope images of human blastocysts.
                        </p>
                    </div>
                    <div className="bg-dark-800/50 p-6 rounded-xl border border-dark-700">
                        <h3 className="text-lg font-semibold text-white mb-2">Ground Truth</h3>
                        <p className="text-slate-400 text-sm leading-relaxed">
                            Labels were provided by senior embryologists using the standard **Gardner Scoring System**
                            (Expansion 1-6, ICM A-C, TE A-C).
                        </p>
                    </div>
                </div>
            </div>

            {/* Model Arch Section */}
            <div className="space-y-6">
                <div className="flex items-center gap-3 border-b border-dark-700 pb-4">
                    <Binary className="h-6 w-6 text-primary-500" />
                    <h2 className="text-2xl font-bold text-white">Model Architecture</h2>
                </div>

                <div className="bg-dark-800/50 p-8 rounded-2xl border border-dark-700 space-y-8">
                    <div className="flex flex-col md:flex-row gap-8 items-center">
                        <div className="flex-1 space-y-4">
                            <div className="flex items-start gap-3">
                                <GitBranch className="h-5 w-5 text-emerald-400 mt-1" />
                                <div>
                                    <h4 className="font-semibold text-white">Backbone: ResNet50V2</h4>
                                    <p className="text-sm text-slate-400">Pre-trained on ImageNet, fine-tuned for morphological feature extraction.</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-3">
                                <GitBranch className="h-5 w-5 text-emerald-400 mt-1" />
                                <div>
                                    <h4 className="font-semibold text-white">Multi-Head Output</h4>
                                    <p className="text-sm text-slate-400">Three dedicated regression heads for independent prediction of Expansion, ICM, and TE scores.</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-3">
                                <GitBranch className="h-5 w-5 text-emerald-400 mt-1" />
                                <div>
                                    <h4 className="font-semibold text-white">Explainability (XAI)</h4>
                                    <p className="text-sm text-slate-400">Integrated Grad-CAM layer to visualize pixel-level attention maps.</p>
                                </div>
                            </div>
                        </div>

                        {/* Metrics Pill Box */}
                        <div className="bg-dark-900/50 p-6 rounded-xl border border-dark-700 w-full md:w-auto min-w-[250px]">
                            <h4 className="text-sm font-uppercase tracking-wider text-slate-500 mb-4">Performance Metrics</h4>
                            <div className="space-y-3">
                                <div className="flex justify-between items-center">
                                    <span className="text-slate-300">Accuracy (±1 Grade)</span>
                                    <span className="text-emerald-400 font-bold font-mono">94.2%</span>
                                </div>
                                <div className="flex justify-between items-center">
                                    <span className="text-slate-300">MAE (Expansion)</span>
                                    <span className="text-emerald-400 font-bold font-mono">0.44</span>
                                </div>
                                <div className="flex justify-between items-center">
                                    <span className="text-slate-300">MAE (ICM)</span>
                                    <span className="text-emerald-400 font-bold font-mono">0.47</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Footer / References */}
            <div className="border-t border-dark-700 pt-8 pb-4">
                <div className="flex items-center gap-2 text-slate-500 text-sm">
                    <FileText className="h-4 w-4" />
                    <span>Reference: </span>
                    <a href="#" className="hover:text-primary-400 transition-colors">Gardner, D. K., & Schoolcraft, W. B. (1999). In vitro culture of human blastocysts.</a>
                </div>
            </div>

        </div>
    );
};
